dissnitt/dissnitt/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mylogin import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mylogin/', include('mylogin.urls')),
    url(r'^todo/', include('todo.urls')),
    url(r'^notes/', include('notes.urls')),
    url(r'^crypto/', include('crypto.urls')),
    url(r'^$', views.home, name="home")
]

dissnitt/todo/urls.py
from django.conf.urls import url
from . import views

app_name = 'todo'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new/$', views.new_project, name='new_project'),
    url(r'^project/(?P<pk>[0-9]+)/edit/$', views.edit_project, name='edit_project'),
    url(r'^project/(?P<pk>[0-9]+)/delete/$', views.delete_project, name='delete_project'),
    url(r'^task/(?P<pk>[0-9]+)/$', views.new_task, name='new_task'),
    url(r'^task/(?P<pk>[0-9]+)/(?P<tk>[0-9]+)/edit/$', views.edit_task, name='edit_task'),
    url(r'^task/(?P<pk>[0-9]+)/(?P<tk>[0-9]+)/delete/$', views.delete_task, name='delete_task'),
    url(r'^subtask/(?P<pk>[0-9]+)/(?P<tk>[0-9]+)/$', views.new_subtask, name='new_subtask'),
    url(r'^subtask/(?P<pk>[0-9]+)/(?P<sk>[0-9]+)/edit/$', views.edit_subtask, name='edit_subtask'),
    url(r'^subtask/(?P<pk>[0-9]+)/(?P<sk>[0-9]+)/delete/$', views.delete_subtask, name='delete_subtask')
]

dissnitt/todo/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    project_name = models.CharField(max_length=30)
    created_date = models.DateTimeField('created_date')
    completed = models.BooleanField()
    description = models.TextField()
    priority = models.IntegerField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.project_name

class Task(models.Model):
    task_name = models.CharField(max_length=30)
    created_date = models.DateTimeField('created_date')
    completed = models.BooleanField()
    description = models.TextField()
    priority = models.IntegerField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.task_name

class SubTask(models.Model):
    sub_name = models.TextField()
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
        return self.sub_name

dissnitt/todo/forms.py
from django import forms
from .models import Project, Task, SubTask


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['project_name', 'description', 'priority', 'completed']

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['task_name', 'priority', 'description', 'completed']

class SubTaskForm(forms.ModelForm):

    class Meta:
        model = SubTask
        fields = ['sub_name']

dissnitt/todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Project, Task, SubTask
from .forms import ProjectForm, TaskForm, SubTaskForm
from django.utils import timezone


class IndexView(LoginRequiredMixin, generic.ListView):

    template_name = 'todo/index.html'
    context_object_name = 'latest_project_list'

    def get_queryset(self):
        user = self.request.user
        return Project.objects.filter(owner__pk=user.pk).order_by('completed', 'priority')


class DetailView(LoginRequiredMixin, generic.DetailView):

    model = Project
    template_name = 'todo/detail.html'

@login_required
def new_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = request.user
            project.completed = False
            project.created_date = timezone.now()
            project.save()
            return redirect('todo:index')

    else:
        form = ProjectForm()

    return render(request, 'todo/project_new.html', {'form': form})

@login_required
def edit_project(request, pk):
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            project.save()
            return redirect('todo:index')
    else:
        form = ProjectForm(instance=project)
    return render(request, 'todo/project_edit.html', {'form': form, 'project':project})

@login_required
def delete_project(request, pk):
    project = get_object_or_404(Project, pk=pk)
    project.delete()

    return redirect('todo:index')

@login_required
def new_task(request, pk):
    project_id = get_object_or_404(Project, pk=pk)
    project = Project.objects.get(pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.project = project_id
            task.completed = False
            task.created_date = timezone.now()
            task.save()
            return redirect('todo:detail', project.pk)
    else:
        form = TaskForm()

    return render(request, 'todo/task_new.html', {'form':form, 'project':project})

@login_required
def edit_task(request, pk, tk):
    task = get_object_or_404(Task, pk=tk)
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task.save()
            return redirect('todo:detail', pk)
    else:
        form = TaskForm(instance=task)

    return render(request, 'todo/task_edit.html', {'form': form, 'project':project, 'task':task})

@login_required
def delete_task(request, pk, tk):
    task = get_object_or_404(Task, pk=tk)
    task.delete()
    return redirect('todo:detail', pk)

@login_required
def new_subtask(request, pk, tk):
    task_id = get_object_or_404(Task, pk=tk)
    project = Project.objects.get(pk=pk)
    if request.method == 'POST':
        form = SubTaskForm(request.POST)
        if form.is_valid():
            subt = form.save(commit=False)
            subt.task = task_id
            subt.completed = False
            subt.created_date = timezone.now()
            subt.save()
            return redirect('todo:detail', pk)
    else:
        form = SubTaskForm()

    return render(request, 'todo/subtask_edit.html', {'form':form, 'task':task_id, 'project':project})

@login_required
def edit_subtask(request, pk, sk):
    subtask = get_object_or_404(SubTask, pk=sk)
    task_id = subtask.task
    # task = Task.objects.get(pk=task_id)
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        form = SubTaskForm(request.POST, instance=subtask)
        if form.is_valid():
            subtask.save()
            return redirect('todo:detail', pk)
    else:
        form = SubTaskForm(instance=subtask)

    return render(request, 'todo/subtask_edit.html', {'form':form, 'task':task_id, 'project':project})

@login_required
def delete_subtask(request, pk, sk):
    subtask = get_object_or_404(SubTask, pk=sk)
    subtask.delete()
    return redirect('todo:detail', pk)

dissnitt/todo/templates/todo/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load todo_app_filters %}
{% block head %}
<title>Project | Dissnitt</title>
<link rel="stylesheet" href="{% static 'todo/css/todo.css' %}">
{% endblock %}

{% block page_header %}<h1>{{ project.priority}} - {{ project.project_name}}</h1>{% endblock %}
{% block sidepage %}
<hr>
<a href="{% url 'todo:new_project' %}">Create New Project</a><br>
<a href="{% url 'todo:edit_project' pk=project.pk %}">Edit Project</a><br>
<a href="{% url 'todo:new_task' pk=project.pk %}">Add A Task</a><br>
{% endblock %}

{% block content %}
<div class="project_detail">
    <p>
        <a href="{% url 'todo:new_project' %}">Create New Project</a> |
        <a href="{% url 'todo:edit_project' pk=project.pk %}">Edit Project</a> |
        <a href="{% url 'todo:new_task' pk=project.pk %}">Add A Task</a>
    </p>
    <h3>Description: {{ project.description }}</h3>

    <table>
        <tr class="todo_table_header">
            <th>P</th>
            <th>Name</th>
             <th>Created</th>
            <th>Description</th>
            <th>Completed</th>
        </tr>
    {% for task in project.task_set.all|sort_by_done %}
        <tr {% if task.completed == True %}
                class="completed"
                {% endif %}>
            <td>{{ task.priority }}</td>
            <td>{{ task.task_name }}</td>
            <td>{{ task.created_date | date:"m/d/Y" }}</td>
            <td class="tddetalign">{{ task.description |urlize | linebreaks }}</td>
            <td>
                {% if task.completed == True %}
                    <img src="{% static 'todo/images/checked.png' %}" alt="True" class="cbox"/>
                {% else %}
                    <img src="{% static 'todo/images/unchecked.png' %}" alt="False" class="cbox"/>
                {% endif %}
            </td>
            <td><a href="{% url 'todo:edit_task' pk=project.pk tk=task.pk %}">Edit</a></td>
            <td><a href="{% url 'todo:delete_task' pk=project.pk tk=task.pk %}">Delete</a></td>
            <td><a href="{% url 'todo:new_subtask' pk=project.pk tk=task.pk %}">+SubT</a></td>
        </tr>
        {% for subtask in task.subtask_set.all %}
        <tr class="subt_rows" >
            <td></td>
            <td></td>
            <td></td>
            <td class="tddetalign" colspan="1">
                {{ subtask.sub_name }}
            </td>
            <td></td>
            <td><a href="{% url 'todo:edit_subtask' pk=project.pk sk=subtask.pk %}">Edit</a></td>
            <td><a href="{% url 'todo:delete_subtask' pk=project.pk sk=subtask.pk %}">Delete</a></td>
            <td></td>
        </tr>
        {% endfor %}
    {% endfor %}
    </table>
</div>
{% endblock %}

dissnitt/todo/templates/todo/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load todo_app_filters %}
{% block head %}
<title>My Projects | Dissnitt</title>
<link rel="stylesheet" href="{% static 'todo/css/todo.css' %}">
<link rel="stylesheet" href="{% static 'todo/css/colorbox.css' %}">
<script type="text/javascript" src="{% static 'todo/javascript/todo.js' %}" ></script>

{% endblock %}
{% block page_header %}<h1>Current Projects</h1>{% endblock %}
{% block sidepage %}
<hr>
<a href="{% url 'todo:new_project' %}">New Project</a><br>
{% endblock %}
{% block content %}
    <div class="todo_info">
        <table>
            <tr class="todo_table_header">
                <th class="btd"></th>
                <th class="ptd">P</th>
                <th class="ntd">Name</th>
                <th class="ctd">Created</th>
                <th class="dtd">Description</th>
                <th class="cotd">Done</th>
                <th></th>
                <th></th>
            </tr>
        </table>
         {% for project in latest_project_list %}
        <table class="projects">
            <tr>
                <td class="btd">
                    <a href="javascript:void(0)"
                       onclick="toggleItemView('pr_{{project.id}}', 'pl_{{project.id}}', 'table')"
                       id="pl_{{project.id}}">
                        +
                    </a>
                </td>
                <td class="ptd" >{{ project.priority }}</td>
                <td class="ntd"><a href="{% url 'todo:detail' project.id %}">{{ project.project_name }}</a></td>
                <td class="ctd">{{ project.created_date | date:"m/d/y"}}</td>
                <td class="dtd">{{ project.description }}</td>
                <td class="cotd">
                    {% if project.completed == True %}
                        <img src="{% static 'todo/images/checked.png' %}" alt="True" class="cbox"/>
                    {% else %}
                        <img src="{% static 'todo/images/unchecked.png' %}" alt="False" class="cbox"/>
                    {% endif %}
                </td>
                <td><a href="{% url 'todo:edit_project' project.id %}">Edit</a></td>
                <td><a href="{% url 'todo:delete_project' project.id %}">Del</a></td>
                <td><a href="{% url 'todo:new_task' pk=project.pk %}">+Task</a></td>
            </tr>
        </table>

        <div class="task_table">
        <table id="pr_{{project.id}}">

         {% for task in project.task_set.all|sort_by_done %}
            <tr {% if task.completed == True %}
                class="completed"
                {% endif %} >
                <td class="btd">
                    <a href="javascript:void(0)"
                       onclick="toggleItemView('st_{{task.id}}', 'tl_{{task.id}}', 'block')"
                       id="tl_{{task.id}}">
                        {% if task.subtask_set.all|length > 0 %}
                        +
                        {% endif %}
                    </a>
                </td>
                <td class="ptd">{{ task.priority }}</td>
                <td class="ntd">{{ task.task_name }}</td>
                <td class="ctd">{{ task.created_date | date:"m/d/y" }}</td>
                <td class="dtd">{{ task.description }}</td>
                <td class="cotd">
                    {% if task.completed == True %}
                        <img src="{% static 'todo/images/checked.png' %}" alt="True" class="cbox"/>
                    {% else %}
                        <img src="{% static 'todo/images/unchecked.png' %}" alt="False" class="cbox"/>
                    {% endif %}
                </td>
                <td><a href="{% url 'todo:edit_task' pk=project.pk tk=task.pk %}">Edit</a></td>
                <td><a href="{% url 'todo:delete_task' pk=project.pk tk=task.pk %}">Del</a></td>
                <td><a href="{% url 'todo:new_subtask' pk=project.pk tk=task.pk %}">+SubT</a></td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td colspan="3">
                    <div id="st_{{ task.id }}" class="subtasks" style="display:none;" >
                        <ul>
                            {% for subtask in task.subtask_set.all %}
                            <li>{{ subtask.sub_name }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </td>
            </tr>
            {% empty %}
            <tr><td>No Tasks Yet</td></tr>
          {% endfor %}
        </table>
        </div>
        {% endfor %}
    </div>


{% endblock %}

dissnitt/todo/templates/todo/project_edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}
<title>Project | Dissnitt</title>
<link rel="stylesheet" href="{% static 'todo/css/todo.css' %}">
{% endblock %}

{% block page_header %}<h1>Create New Project</h1>{% endblock %}

{% block content %}
<div class="project_form">
    <form method="POST">{% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.project_name.errors }}
        {{ form.project_name.label_tag }}
        {{ form.project_name }}
        <br>
        {{ form.priority.errors }}
        {{ form.priority.label_tag }}
        {{ form.priority }}
        <br>
        {{ form.completed.errors }}
        {{ form.completed.label_tag }}
        {{ form.completed }}
        <br>
        {{ form.description.errors }}
        {{ form.description.label_tag }}
        {{ form.description }}
        <br>
        <button type="submit" >Save</button>
    </form>
</div>
{% endblock %}

dissnitt/todo/templates/todo/project_new.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}
<title>Project | Dissnitt</title>
<link rel="stylesheet" href="{% static 'todo/css/todo.css' %}">
{% endblock %}

{% block page_header %}<h1>Create New Project</h1>{% endblock %}


{% block content %}
<div class="project_form">
    <form method="POST">{% csrf_token %}

        <table>
            <tr>
                <td>
                    {{ form.non_field_errors }}
                    {{ form.project_name.errors }}
                    {{ form.project_name.label_tag }}
                </td>
                <td >
                    {{ form.project_name }}
                </td>
            </tr>
            <tr>
                <td>
                    {{ form.priority.errors }}
                    {{ form.priority.label_tag }}
                </td>
                <td>
                    {{ form.priority }}
                </td>
            </tr>

            <tr>
                <td>
                    {{ form.description.errors }}
                    {{ form.description.label_tag }}
                </td>
                <td>
                    {{ form.description }}
                </td>
            </tr>

            <tr>
                <td colspan="2" style="text-align:center;" >
                    <button class="pbutton" type="submit" >Create Project</button>
                </td>
            </tr>
            </table>
    </form>
</div>
{% endblock %}

dissnitt/todo/templates/todo/subtask_edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}
<title>Project | Dissnitt</title>
<link rel="stylesheet" href="{% static 'todo/css/todo.css' %}">
{% endblock %}
{% block sidepage %}
<hr>
    <a href="{% url 'todo:new_project' %}">Create New Project</a><br>
    <a href="{% url 'todo:detail' project.pk %}">Project Details</a>

{% endblock %}
{% block page_header %}
    <h1>
        Add Sub Task to {{ task.task_name }}
    </h1>
{% endblock %}

{% block content %}
<div class="project_form">
     <form method="POST">{% csrf_token %}
        <table>
            <tr>
                 <td>
                    {{ form.non_field_errors }}
                    {{ form.sub_name.errors }}
                    {{ form.sub_name.label_tag }}
                 </td>
            </tr>
            <tr>
                 <td>
                    {{ form.sub_name }}
                 </td>
            </tr>
            <tr>
                <td colspan="1">
                    <button style="margin-left: 25%;" class="pbutton" type="submit" >Save</button>
                </td>
            </tr>
        </table>
     </form>

    <div class="sub_deets">
        <h2>Project Name: {{ project.project_name }}</h2>
        <h2>Task Name: {{ task.task_name }}</h2>
         <ul>
             {% for subtask in task.subtask_set.all %}
             <li>{{ subtask.sub_name }}</li>
             {% endfor %}
         </ul>
    </div>
</div>
{% endblock %}

dissnitt/todo/templates/todo/task_edit.html
{% extends 'base.html' %}
{% load todo_app_filters %}
{% load staticfiles %}
{% block head %}
<title>Project | Dissnitt</title>
<link rel="stylesheet" href="{% static 'todo/css/todo.css' %}">
{% endblock %}

{% block sidepage %}
<hr>
    <a href="{% url 'todo:new_project' %}">Create New Project</a><br>
    <a href="{% url 'todo:new_task' pk=project.pk %}">Add A Task</a><br>
{% endblock %}

{% block page_header %}
    <h1>
        Change <span style="font-style: italic;">{{ task.task_name }}</span> :
        <a href="{% url 'todo:detail' pk=project.pk %}">{{ project.project_name}}</a>
    </h1>
{% endblock %}

{% block content %}

<div class="project_form">
    <form method="POST">{% csrf_token %}
        <table>
            <tr>
                <td>
                    {{ form.non_field_errors }}
                    {{ form.task_name.errors }}
                    {{ form.task_name.label_tag }}
                </td>
                <td >
                    {{ form.task_name }}
                </td>
            </tr>
            <tr>
                <td>
                    {{ form.priority.errors }}
                    {{ form.priority.label_tag }}
                </td>
                <td>
                    {{ form.priority }}
                </td>
            </tr>

            <tr>
                <td>
                    {{ form.description.errors }}
                    {{ form.description.label_tag }}
                </td>
                <td>
                    {{ form.description }}
                </td>
            </tr>
            <tr>
                <td>
                    {{ form.completed.errors }}
                    {{ form.completed.label_tag }}
                    {{ form.completed }}
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align:center;" >
                    <button class="pbutton" type="submit" >Save Changes</button>
                </td>
            </tr>
        </table>
    </form>

    <div class="incomplete_tasks">
        <h3>Open Tasks:</h3>
    {% for task in project.task_set.all|not_complete %}
        <p>{{ task.task_name }}</p>
    {% endfor %}
    </div>

</div>
{% endblock %}

dissnitt/todo/templates/todo/task_new.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load todo_app_filters %}
{% block head %}
<title>Project | Dissnitt</title>
<link rel="stylesheet" href="{% static 'todo/css/todo.css' %}">
{% endblock %}

{% block sidepage %}
<hr>
    <a href="{% url 'todo:new_project' %}">Create New Project</a><br>

{% endblock %}

{% block page_header %}
    <h1>
        New Task for  <a href="{% url 'todo:detail' pk=project.pk %}">{{ project.project_name}}</a>
    </h1>
{% endblock %}

{% block content %}

<div class="project_form">
    <form method="POST">{% csrf_token %}
        <table>
            <tr>
                <td>
                    {{ form.non_field_errors }}
                    {{ form.task_name.errors }}
                    {{ form.task_name.label_tag }}
                </td>
                <td >
                    {{ form.task_name }}
                </td>
            </tr>
            <tr>
                <td>
                    {{ form.priority.errors }}
                    {{ form.priority.label_tag }}
                </td>
                <td>
                    {{ form.priority }}
                </td>
            </tr>

            <tr>
                <td>
                    {{ form.description.errors }}
                    {{ form.description.label_tag }}
                </td>
                <td>
                    {{ form.description }}
                </td>
            </tr>

            <tr>
                <td colspan="2" style="text-align:center;" >
                    <button class="pbutton" type="submit" >Create Task</button>
                </td>
            </tr>
        </table>
    </form>

     <div class="incomplete_tasks">
        <h3>Open Tasks:</h3>
    {% for task in project.task_set.all|not_complete %}
        <p>{{ task.task_name }}</p>
    {% endfor %}
    </div>
</div>
{% endblock %}