dissnitt/crypto/urls.py
from django.conf.urls import url

from . import views

app_name = 'crypto'

urlpatterns = [
    url(r'^index', views.index, name='index'),
    url(r'^pdatag/(?P<table>[a-z]+)/$', views.pdatag, name='pdatag')
]

dissnitt/dissnitt/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mylogin import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mylogin/', include('mylogin.urls')),
    url(r'^todo/', include('todo.urls')),
    url(r'^notes/', include('notes.urls')),
    url(r'^crypto/', include('crypto.urls')),
    url(r'^$', views.home, name="home")
]

dissnitt/todo/urls.py
from django.conf.urls import url
from . import views

app_name = 'todo'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new/$', views.new_project, name='new_project'),
    url(r'^project/(?P<pk>[0-9]+)/edit/$', views.edit_project, name='edit_project'),
    url(r'^project/(?P<pk>[0-9]+)/delete/$', views.delete_project, name='delete_project'),
    url(r'^task/(?P<pk>[0-9]+)/$', views.new_task, name='new_task'),
    url(r'^task/(?P<pk>[0-9]+)/(?P<tk>[0-9]+)/edit/$', views.edit_task, name='edit_task'),
    url(r'^task/(?P<pk>[0-9]+)/(?P<tk>[0-9]+)/delete/$', views.delete_task, name='delete_task'),
    url(r'^subtask/(?P<pk>[0-9]+)/(?P<tk>[0-9]+)/$', views.new_subtask, name='new_subtask'),
    url(r'^subtask/(?P<pk>[0-9]+)/(?P<sk>[0-9]+)/edit/$', views.edit_subtask, name='edit_subtask'),
    url(r'^subtask/(?P<pk>[0-9]+)/(?P<sk>[0-9]+)/delete/$', views.delete_subtask, name='delete_subtask')
]

dissnitt/crypto/models.py
from django.db import models


class Bitcoin(models.Model):
    ptime = models.DateTimeField()
    gemini_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    coinbase_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    kraken_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    binance_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    bitfinex_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    bitstamp_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    gdax_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)


class Etherium(models.Model):
    ptime = models.DateTimeField()
    gemini_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    coinbase_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    kraken_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    binance_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    bitfinex_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    bitstamp_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    gdax_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)


class EtheriumBTC(models.Model):
    ptime = models.DateTimeField()
    gemini_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    kraken_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    binance_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    bitfinex_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    bitstamp_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    gdax_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)


class Litecoin(models.Model):
    ptime = models.DateTimeField()
    coinbase_price = models.DecimalField(max_digits=20, decimal_places=4, default=0.000)
    kraken_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    binance_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    bitfinex_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    bitstamp_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    gdax_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)


class LitecoinBTC(models.Model):
    ptime = models.DateTimeField()
    kraken_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    binance_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    bitfinex_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    bitstamp_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    gdax_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)


class RippleBTC(models.Model):
    ptime = models.DateTimeField()
    kraken_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    binance_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    bitfinex_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    bitstamp_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)


class MoneroBTC(models.Model):
    ptime = models.DateTimeField()
    kraken_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    binance_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    bitfinex_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)


class BitcashBTC(models.Model):
    ptime = models.DateTimeField()
    kraken_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    binance_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    bitfinex_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)
    bitstamp_price = models.DecimalField(max_digits=20, decimal_places=6, default=0.000)

dissnitt/crypto/forms.py
from django import forms


class TimeForm(forms.Form):

    time_frame = forms.IntegerField(label="Number of Minutes", min_value=5, max_value=1000)

dissnitt/crypto/views.py
from collections import namedtuple
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .calcs import CalcClass
from .forms import TimeForm
from .visualizer import GraphClass
from .models import Bitcoin, Etherium, EtheriumBTC, Litecoin, LitecoinBTC, RippleBTC, MoneroBTC, BitcashBTC


@login_required(login_url='/mylogin/login/')
def index(request):

    btc_le = Bitcoin.objects.last()

    ethbtc_data = CalcClass().views_data(EtheriumBTC.objects.last())
    ltcbtc_data = CalcClass().views_data(LitecoinBTC.objects.last())
    xrpbtc_data = CalcClass().views_data(RippleBTC.objects.last())
    xmrbtc_data = CalcClass().views_data(MoneroBTC.objects.last())
    bchbtc_data = CalcClass().views_data(BitcashBTC.objects.last())

    btc_price = float(btc_le.gdax_price)
    ethbtc_usd = btc_price * ethbtc_data[0]
    ltcbtc_usd = btc_price * ltcbtc_data[0]
    xrpbtc_usd = btc_price * xrpbtc_data[0]
    xmrbtc_usd = btc_price * xmrbtc_data[0]
    bchbtc_usd = btc_price * bchbtc_data[0]

    context = {
               'btc': CalcClass().views_data(btc_le),
               'eth': CalcClass().views_data(Etherium.objects.last()),
               'ltc': CalcClass().views_data(Litecoin.objects.last()),
               'ethbtc': ethbtc_data,
               'ethbtc_usd': ethbtc_usd,
               'ethbtc_start_usd': ethbtc_data[3] * btc_price,
               'ethbtc_end_usd': ethbtc_data[4] * btc_price,
               'ltcbtc': ltcbtc_data,
               'ltcbtc_usd': ltcbtc_usd,
               'ltcbtc_start_usd': ltcbtc_data[3] * btc_price,
               'ltcbtc_end_usd': ltcbtc_data[4] * btc_price,
               'xrpbtc': xrpbtc_data,
               'xrpbtc_usd': xrpbtc_usd,
               'xrpbtc_start_usd': xrpbtc_data[3] * btc_price,
               'xrpbtc_end_usd': xrpbtc_data[4] * btc_price,
               'xmrbtc': xmrbtc_data,
               'xmrbtc_usd': xmrbtc_usd,
               'xmrbtc_start_usd': xmrbtc_data[3] * btc_price,
               'xmrbtc_end_usd': xmrbtc_data[4] * btc_price,
               'bchbtc': bchbtc_data,
               'bchbtc_usd': bchbtc_usd,
               'bchbtc_start_usd': bchbtc_data[3] * btc_price,
               'bchbtc_end_usd': bchbtc_data[4] * btc_price,
              }

    return render(request, 'crypto/index.html', context)


@login_required(login_url='/mylogin/login/')
def pdatag(request, table):

    cdict = {'bitcoin': 'BTC/USD',
             'etherium': 'ETH/USD',
             'etheriumbtc': 'ETH/BTC',
             'litecoin': 'LTC/USD',
             'litecoinbtc': 'LTC/BTC',
             'monerobtc': 'XMR/BTC',
             'ripplebtc': 'XRP/BTC',
             'bitcashbtc': 'BCH/BTC'}

    cur = cdict.get(table)

    if request.method == 'POST':
        form = TimeForm(request.POST)
        if form.is_valid():
            tf = form.cleaned_data['time_frame']
            script, div = GraphClass(table).graph_data(tf)
            context = {"script": script,
                       "div": div,
                       "form": form,
                       'cur': cur}

            return render(request, 'crypto/btc.html', context)

    else:
        form = TimeForm()
        script, div = GraphClass(table).graph_data()
        context = {"script": script,
                   "div": div,
                   "form": form,
                   "cur": cur}

        return render(request, 'crypto/btc.html', context)

dissnitt/crypto/templates/crypto/btc.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}
    <title>Crypto | Dissnitt</title>
     <link rel="stylesheet" href="{% static 'crypto/css/crypto.css' %}">
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.css" rel="stylesheet" type="text/css">
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.13.min.css" rel="stylesheet" type="text/css">
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.js"></script>
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.13.min.js"></script>
{% endblock %}
{% block page_header %}
    <h1>{{ cur }} by Exchange </h1>
{% endblock %}
{% block content %}
    <div class="tf_div">
         <form method="POST">
             {% csrf_token %}
            <p>
                {{ form.non_field_errors }}
                {{ form.title.errors }}
            </p>
            <p>
                {{ form.time_frame }}
            </p>
             <button class="tfbutton" type="submit" >Set Look Back Period in Minutes</button>
         </form>
    </div>
    <div id="bokeh_btc">
        {{ div|safe }}
        <script src="http://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.js"></script>
        <script src="http://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.13.min.js"></script>
        {{ script|safe}}
            <script type="text/javascript">
                setTimeout( function() {
                    location.reload(forceGet=true);
                    }, 300000);
            </script>
    </div>
{% endblock %}

dissnitt/crypto/templates/crypto/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crypto_app_filters %}
{% block head %}
    <title>Crypto | Dissnitt</title>
    <link rel="stylesheet" href="{% static 'crypto/css/crypto.css' %}">
    <script type="text/javascript" src="{% static 'crypto/javascript/crypto.js' %}" ></script>
{% endblock %}
{% block page_header %}
    <h1>Crypto Arbitrage</h1>
{% endblock %}
{% block content %}
<div class="crypto_index">
    <div class="row1">
        <div class="bitp" id="btc_d">
            <table>
                <tr>
                    <th class="static">Bitcoin/ USD</th>
                </tr>
                <tr>
                    <td class="pbtc_usd" >$ {{ btc.0|make_usd  }}</td>
                </tr>
                <tr>
                    <td class="pbtc_usd">{{ btc.5|floatformat:2 }} %</td>
                </tr>
                <tr>
                    <td class="static">{{ btc.1 }} -> {{ btc.2 }}</td>
                </tr>
                 <tr>
                    <td class="static">${{ btc.3|make_usd }} -> ${{ btc.4|make_usd }}</td>
                </tr>
                <tr>
                    <td class="tlink"><a href="{% url 'crypto:pdatag' 'bitcoin' %}">View Data</a></td>
                </tr>
            </table>
        </div>
        <div class="ethp" id="eth_d">
            <table>
                <tr>
                    <th class="static">Etherium/ USD</th>
                </tr>
                <tr>
                    <td class="peth_usd" >$ {{ eth.0|make_usd }}</td>
                </tr>
                <tr>
                    <td class="peth_usd">{{ eth.5|floatformat:2 }} %</td>
                </tr>
                <tr>
                    <td class="static">{{ eth.1 }} -> {{ eth.2 }}</td>
                </tr>
                <tr>
                    <td class="static">${{ eth.3|make_usd }} -> ${{ eth.4|make_usd }}</td>
                </tr>
                <tr>
                    <td class="tlink"><a href="{% url 'crypto:pdatag' 'etherium' %}">View Data</a></td>
                </tr>
            </table>
        </div>
         <div class="ethp" id="ltc_d">
            <table>
                <tr>
                    <th class="static">Litecoin/ USD</th>
                </tr>
                <tr>
                    <td class="pltc_usd" >$ {{ ltc.0|make_usd }}</td>
                </tr>
                <tr>
                    <td class="pltc_usd">{{ ltc.5|floatformat:2 }} %</td>
                </tr>
                <tr>
                    <td class="static">{{ ltc.1 }} -> {{ ltc.2 }}</td>
                </tr>
                <tr>
                    <td class="static">${{ ltc.3|make_usd }} -> ${{ ltc.4|make_usd }}</td>
                </tr>
                <tr>
                    <td class="tlink"><a href="{% url 'crypto:pdatag' 'litecoin' %}">View Data</a></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row2">
         <div class="ethpbtc" id="bchbtc_d">
            <table>
                <tr>
                    <th class="static">Bitcoin Cash/ BTC</th>
                </tr>
                <tr>
                    <td class="pbch_btc" > {{ bchbtc.0|floatformat:6 }} (${{ bchbtc_usd|make_usd }})</td>
                </tr>
                <tr>
                    <td class="pbch_btc">{{ bchbtc.5|floatformat:4}} %</td>
                </tr>
                <tr>
                    <td class="static">{{ bchbtc.1 }} -> {{ bchbtc.2 }}</td>
                </tr>
                <tr>
                    <td class="static">{{ bchbtc.3 }} -> {{ bchbtc.4 }}</td>
                </tr>
                <tr>
                    <td class="static">${{ bchbtc_start_usd|make_usd }} -> ${{ bchbtc_end_usd|make_usd }}</td>
                </tr>
                <tr>
                    <td class="tlinkbtc"><a href="{% url 'crypto:pdatag' 'bitcashbtc' %}">View Data</a></td>
                </tr>
            </table>
        </div>
        <div class="ethpbtc" id="ethbtc_d">
            <table>
                <tr>
                    <th class="static">Etherium/ BTC</th>
                </tr>
                <tr>
                    <td class="peth_btc" > {{ ethbtc.0|floatformat:6 }} (${{ ethbtc_usd|make_usd }})</td>
                </tr>
                <tr>
                    <td class="peth_btc">{{ ethbtc.5|floatformat:4}} %</td>
                </tr>
                <tr>
                    <td class="static">{{ ethbtc.1 }} -> {{ ethbtc.2 }}</td>
                </tr>
                <tr>
                    <td class="static">{{ ethbtc.3 }} -> {{ ethbtc.4 }}</td>
                </tr>
                <tr>
                    <td class="static">${{ ethbtc_start_usd|make_usd }} -> ${{ ethbtc_end_usd|make_usd }}</td>
                </tr>
                <tr>
                    <td class="tlinkbtc"><a href="{% url 'crypto:pdatag' 'etheriumbtc' %}">View Data</a></td>
                </tr>
            </table>
        </div>
         <div class="ethpbtc" id="ltcbtc_d">
            <table>
                <tr>
                    <th class="static">Litecoin/ BTC</th>
                </tr>
                <tr>
                    <td class="pltc_btc" > {{ ltcbtc.0|floatformat:6 }} (${{ ltcbtc_usd|make_usd }})</td>
                </tr>
                <tr>
                    <td class="pltc_btc">{{ ltcbtc.5|floatformat:4}} %</td>
                </tr>
                <tr>
                    <td class="static">{{ ltcbtc.1 }} -> {{ ltcbtc.2 }}</td>
                </tr>
                <tr>
                    <td class="static">{{ ltcbtc.3 }} -> {{ ltcbtc.4 }}</td>
                </tr>
                 <tr>
                    <td class="static">${{ ltcbtc_start_usd|make_usd }} -> ${{ ltcbtc_end_usd|make_usd }}</td>
                </tr>
                <tr>
                    <td class="tlinkbtc"><a href="{% url 'crypto:pdatag' 'litecoinbtc' %}">View Data</a></td>
                </tr>
            </table>
        </div>
         <div class="ethpbtc" id="xmrbtc_d">
            <table>
                <tr>
                    <th class="static">Monero/ BTC</th>
                </tr>
                <tr>
                    <td class="pxmr_btc" > {{ xmrbtc.0|floatformat:6 }} (${{ xmrbtc_usd|make_usd }})</td>
                </tr>
                <tr>
                    <td class="pxmr_btc">{{ xmrbtc.5|floatformat:4}} %</td>
                </tr>
                <tr>
                    <td class="static">{{ xmrbtc.1 }} -> {{ xmrbtc.2 }}</td>
                </tr>
                <tr>
                    <td class="static">{{ xmrbtc.3 }} -> {{ xmrbtc.4 }}</td>
                </tr>
                 <tr>
                    <td class="static">${{ xmrbtc_start_usd|make_usd }} -> ${{ xmrbtc_end_usd|make_usd }}</td>
                </tr>
                <tr>
                    <td class="tlinkbtc"><a href="{% url 'crypto:pdatag' 'monerobtc' %}">View Data</a></td>
                </tr>
            </table>
        </div>
         <div class="ethpbtc" id="xrpbtc_d">
            <table>
                <tr>
                    <th class="static">Ripple/ BTC</th>
                </tr>
                <tr>
                    <td class="pxrp_btc" > {{ xrpbtc.0|floatformat:6 }} (${{ xrpbtc_usd|make_usd }})</td>
                </tr>
                <tr>
                    <td class="pxrp_btc">{{ xrpbtc.5|floatformat:4}} %</td>
                </tr>
                <tr>
                    <td class="static">{{ xrpbtc.1 }} -> {{ xrpbtc.2 }}</td>
                </tr>
                <tr>
                    <td class="static">{{ xrpbtc.3 }} -> {{ xrpbtc.4 }}</td>
                </tr>
                 <tr>
                    <td class="static">${{ xrpbtc_start_usd|make_usd }} -> ${{ xrpbtc_end_usd|make_usd }}</td>
                </tr>
                <tr>
                    <td class="tlinkbtc"><a href="{% url 'crypto:pdatag' 'ripplebtc' %}">View Data</a></td>
                </tr>
            </table>
        </div>
    </div>
</div>
<script>
    document.getElementById("btc_d").addEventListener("load", profitBGcolor('pbtc_usd', '{{ btc.0 }}'));
    document.getElementById("eth_d").addEventListener("load", profitBGcolor('peth_usd', '{{ eth.0 }}'));
    document.getElementById("ltc_d").addEventListener("load", profitBGcolor('pltc_usd', '{{ ltc.0 }}'));
    document.getElementById("bchbtc_d").addEventListener("load", profitBGcolor('pbch_btc', '{{ bchbtc.0 }}'));
    document.getElementById("ethbtc_d").addEventListener("load", profitBGcolor('peth_btc', '{{ ethbtc.0 }}'));
    document.getElementById("ltcbtc_d").addEventListener("load", profitBGcolor('pltc_btc', '{{ ltcbtc.0 }}'));
    document.getElementById("xmrbtc_d").addEventListener("load", profitBGcolor('pxmr_btc', '{{ xmrbtc.0 }}'));
    document.getElementById("xrpbtc_d").addEventListener("load", profitBGcolor('pxrp_btc', '{{ xrpbtc.0 }}'));

</script>
{% endblock %}