dissnitt/crypto/urls.py
from django.conf.urls import url

from . import views

app_name = 'crypto'

urlpatterns = [
    url(r'^index', views.index, name='index'),
    url(r'^pdatag/(?P<table>[a-z]+)/$', views.pdatag, name='pdatag')
]

dissnitt/dissnitt/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mylogin import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mylogin/', include('mylogin.urls')),
    url(r'^todo/', include('todo.urls')),
    url(r'^notes/', include('notes.urls')),
    url(r'^crypto/', include('crypto.urls')),
    url(r'^$', views.home, name="home")
]

dissnitt/mylogin/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name='mylogin'

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'mylogin/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/mylogin/login'}, name='logout'),
    url(r'^home/$', views.home, name='home')
]

dissnitt/notes/urls.py
from django.conf.urls import url
from . import views

app_name = 'notes'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new/$', views.new_note, name='new_note'),
    url(r'^note/(?P<pk>[0-9]+)/edit/$', views.edit_note, name='edit_note'),
    url(r'^note/(?P<pk>[0-9]+)/delete/$', views.delete_note, name='delete_note'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.ByTagDetailView.as_view(), name='by_tag'),
    url(r'^tags/$', views.TagIndexView.as_view(), name='tags'),
    url(r'^tag/(?P<pk>[0-9]+)/delete/$', views.delete_tag, name='delete_tag')
]

dissnitt/todo/urls.py
from django.conf.urls import url
from . import views

app_name = 'todo'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new/$', views.new_project, name='new_project'),
    url(r'^project/(?P<pk>[0-9]+)/edit/$', views.edit_project, name='edit_project'),
    url(r'^project/(?P<pk>[0-9]+)/delete/$', views.delete_project, name='delete_project'),
    url(r'^task/(?P<pk>[0-9]+)/$', views.new_task, name='new_task'),
    url(r'^task/(?P<pk>[0-9]+)/(?P<tk>[0-9]+)/edit/$', views.edit_task, name='edit_task'),
    url(r'^task/(?P<pk>[0-9]+)/(?P<tk>[0-9]+)/delete/$', views.delete_task, name='delete_task'),
    url(r'^subtask/(?P<pk>[0-9]+)/(?P<tk>[0-9]+)/$', views.new_subtask, name='new_subtask'),
    url(r'^subtask/(?P<pk>[0-9]+)/(?P<sk>[0-9]+)/edit/$', views.edit_subtask, name='edit_subtask'),
    url(r'^subtask/(?P<pk>[0-9]+)/(?P<sk>[0-9]+)/delete/$', views.delete_subtask, name='delete_subtask')
]

dissnitt/mylogin/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from notes.models import Tag, Note
from todo.models import Project


@login_required(login_url='/mylogin/login/')
def home(request):
    user = request.user
    projects = Project.objects.filter(owner__pk=user.pk)
    cprojects = projects.filter(owner__pk=user.pk).filter(completed=True)

    try:
        cperc = round((float(len(cprojects))/float(len(projects)))*100, 2)

    except ZeroDivisionError:
        cperc = 0.00

    notes = Note.objects.filter(owner__pk=user.pk)
    tags = Tag.objects.filter(owner__pk=user.pk)

    context = {
        'projects':projects,
        'cprojects': cprojects,
        'cperc': cperc,
        'notes': notes,
        'tags': tags
    }

    return render(request, 'mylogin/home.html', context)

dissnitt/mylogin/templates/base.html
{% load staticfiles %}

<html>

<head>
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'mylogin/css/base.css' %}">
    <script type="text/javascript" src="{% static 'todo/javascript/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'todo/javascript/jquery.colorbox.js' %}"></script>
</head>
<head>
    {% block head %}
    {% endblock %}
</head>

<body>
    <div class="ppage">
        <div class="header">
            <div class="hcorner">
                <h1>CharlieI.org</h1>
            </div>
            <div class="page_header">
                {% block page_header %}{% endblock %}
            </div>
        </div>
        <div class="side">
            <div class="side_navigation">
                <a href="{% url 'mylogin:logout' %}">Logout</a>
                <br/>
                <a href="{% url 'mylogin:home' %}">Home</a>
                <br/>
                <a href="{% url 'todo:index' %}">Projects</a>
                <br/>
                <a href="{% url 'notes:index' %}">Notes</a>
                <br/>
                <a href="{% url 'crypto:index' %}">Crypto</a>
                {% block sidepage %}
                {% endblock %}
            </div>
        </div>

        <div class="main">
            {% block content %}
            {% endblock %}

        </div>
    </div>
</body>
</html>