dissnitt/dissnitt/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mylogin import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mylogin/', include('mylogin.urls')),
    url(r'^todo/', include('todo.urls')),
    url(r'^notes/', include('notes.urls')),
    url(r'^crypto/', include('crypto.urls')),
    url(r'^$', views.home, name="home")
]

dissnitt/notes/urls.py
from django.conf.urls import url
from . import views

app_name = 'notes'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new/$', views.new_note, name='new_note'),
    url(r'^note/(?P<pk>[0-9]+)/edit/$', views.edit_note, name='edit_note'),
    url(r'^note/(?P<pk>[0-9]+)/delete/$', views.delete_note, name='delete_note'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.ByTagDetailView.as_view(), name='by_tag'),
    url(r'^tags/$', views.TagIndexView.as_view(), name='tags'),
    url(r'^tag/(?P<pk>[0-9]+)/delete/$', views.delete_tag, name='delete_tag')
]

dissnitt/todo/urls.py
from django.conf.urls import url
from . import views

app_name = 'todo'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^new/$', views.new_project, name='new_project'),
    url(r'^project/(?P<pk>[0-9]+)/edit/$', views.edit_project, name='edit_project'),
    url(r'^project/(?P<pk>[0-9]+)/delete/$', views.delete_project, name='delete_project'),
    url(r'^task/(?P<pk>[0-9]+)/$', views.new_task, name='new_task'),
    url(r'^task/(?P<pk>[0-9]+)/(?P<tk>[0-9]+)/edit/$', views.edit_task, name='edit_task'),
    url(r'^task/(?P<pk>[0-9]+)/(?P<tk>[0-9]+)/delete/$', views.delete_task, name='delete_task'),
    url(r'^subtask/(?P<pk>[0-9]+)/(?P<tk>[0-9]+)/$', views.new_subtask, name='new_subtask'),
    url(r'^subtask/(?P<pk>[0-9]+)/(?P<sk>[0-9]+)/edit/$', views.edit_subtask, name='edit_subtask'),
    url(r'^subtask/(?P<pk>[0-9]+)/(?P<sk>[0-9]+)/delete/$', views.delete_subtask, name='delete_subtask')
]

dissnitt/notes/models.py
from django.db import models
from django.contrib.auth.models import User


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Note(models.Model):
    title = models.CharField(max_length=30)
    body = models.TextField()
    created_date = models.DateTimeField('date created')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

dissnitt/notes/forms.py
from django import forms
from .models import Note, Tag


class NoteForm(forms.ModelForm):

    class Meta:
        model = Note
        fields = ['title', 'body']

        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Note Title'}),
            'body': forms.Textarea( attrs={'placeholder': 'Write stuff here'}),
        }


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = ['name']

dissnitt/notes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic, View
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .models import Note, Tag
from .forms import NoteForm, TagForm
from django.views.generic.detail import SingleObjectMixin


class IndexView(LoginRequiredMixin, generic.ListView):

    template_name = 'notes/index.html'
    context_object_name = 'note_list'

    def get_queryset(self):
        user = self.request.user
        notes = Note.objects.filter(owner__pk=user.id).order_by('created_date')
        paginator = Paginator(notes, 8)
        page = self.request.GET.get('page')
        try:
            note_page = paginator.page(page)
        except PageNotAnInteger:
            note_page = paginator.page(1)
        except EmptyPage:
            note_page = paginator.page(paginator.num_pages)
        return note_page

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        user = self.request.user
        context['tags'] = get_tags(user.id)
        return context


class TagFormView(SingleObjectMixin, generic.FormView):

    form_class = TagForm
    model = Tag

    def post(self, request, *args, **kwargs):
        form = request.POST
        tag_names = str(form['name']).split(" ")
        note = Note.objects.get(pk=kwargs['pk'])

        for n in tag_names:
            try:
                tag_obj = Tag.objects.get(name=n)

            except Tag.DoesNotExist:
                tag_obj = Tag(name=n, owner=request.user)
                tag_obj.save()

            note.tags.add(tag_obj)

        return redirect('notes:detail', note.pk)

class NoteView(LoginRequiredMixin, generic.DetailView):

    model = Note
    template_name = 'notes/detail.html'

    def get_context_data(self, **kwargs):
        context = super(NoteView, self).get_context_data(**kwargs)
        user = self.request.user
        context['form'] = TagForm
        context['tags'] = get_tags(user.id)
        return context


class DetailView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        view = NoteView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = TagFormView.as_view()
        return view(request, *args, **kwargs)


def get_notes(user_id):
    return Note.objects.filter(owner=user_id)

def get_tags(user_id):
    all_tags = Tag.objects.all().filter(owner=user_id).order_by('name')
    tags_w_count = [t for t in all_tags if t.note_set.all().count() > 0]
    return tags_w_count

@login_required
def new_note(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.owner = request.user
            note.created_date = timezone.now()
            note.save()
            return redirect('notes:index')

    else:
        form = NoteForm()

    user = request.user
    notes = get_notes(user.id)

    return render(request, 'notes/note_new.html', {'form': form, 'notes': notes})

@login_required
def edit_note(request, pk):
    note = get_object_or_404(Note, pk=pk)
    if request.method == 'POST':
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect('notes:index')
    else:
        form = NoteForm(instance=note)

    user = request.user
    notes = get_notes(user.id)

    return render(request, 'notes/note_new.html', {'form': form, 'note': note, 'notes':notes})

@login_required
def delete_note(request, pk):
    note = get_object_or_404(Note, pk=pk)
    note.delete()
    return redirect('notes:index')


@login_required
def delete_tag(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    tag.delete()
    return redirect('notes:tags')


class ByTagDetailView(LoginRequiredMixin, generic.DetailView):

    model = Tag
    template_name = 'notes/by_tag_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ByTagDetailView, self).get_context_data(**kwargs)
        user = self.request.user
        context['tags'] = get_tags(user.id)
        return context

class TagIndexView(LoginRequiredMixin, generic.ListView):

    template_name = 'notes/tag_index.html'
    context_object_name = 'tag_list'

    def get_queryset(self):
        user = self.request.user
        tags = get_tags(user.id)
        tags.sort(key=lambda x: len(x.note_set.all()), reverse=True)
        paginator = Paginator(tags, 20)
        page = self.request.GET.get('page')
        try:
            tag_page = paginator.page(page)
        except PageNotAnInteger:
            tag_page = paginator.page(1)
        except EmptyPage:
            tag_page = paginator.page(paginator.num_pages)
        return tag_page

dissnitt/todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Project, Task, SubTask
from .forms import ProjectForm, TaskForm, SubTaskForm
from django.utils import timezone


class IndexView(LoginRequiredMixin, generic.ListView):

    template_name = 'todo/index.html'
    context_object_name = 'latest_project_list'

    def get_queryset(self):
        user = self.request.user
        return Project.objects.filter(owner__pk=user.pk).order_by('completed', 'priority')


class DetailView(LoginRequiredMixin, generic.DetailView):

    model = Project
    template_name = 'todo/detail.html'

@login_required
def new_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = request.user
            project.completed = False
            project.created_date = timezone.now()
            project.save()
            return redirect('todo:index')

    else:
        form = ProjectForm()

    return render(request, 'todo/project_new.html', {'form': form})

@login_required
def edit_project(request, pk):
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            project.save()
            return redirect('todo:index')
    else:
        form = ProjectForm(instance=project)
    return render(request, 'todo/project_edit.html', {'form': form, 'project':project})

@login_required
def delete_project(request, pk):
    project = get_object_or_404(Project, pk=pk)
    project.delete()

    return redirect('todo:index')

@login_required
def new_task(request, pk):
    project_id = get_object_or_404(Project, pk=pk)
    project = Project.objects.get(pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.project = project_id
            task.completed = False
            task.created_date = timezone.now()
            task.save()
            return redirect('todo:detail', project.pk)
    else:
        form = TaskForm()

    return render(request, 'todo/task_new.html', {'form':form, 'project':project})

@login_required
def edit_task(request, pk, tk):
    task = get_object_or_404(Task, pk=tk)
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task.save()
            return redirect('todo:detail', pk)
    else:
        form = TaskForm(instance=task)

    return render(request, 'todo/task_edit.html', {'form': form, 'project':project, 'task':task})

@login_required
def delete_task(request, pk, tk):
    task = get_object_or_404(Task, pk=tk)
    task.delete()
    return redirect('todo:detail', pk)

@login_required
def new_subtask(request, pk, tk):
    task_id = get_object_or_404(Task, pk=tk)
    project = Project.objects.get(pk=pk)
    if request.method == 'POST':
        form = SubTaskForm(request.POST)
        if form.is_valid():
            subt = form.save(commit=False)
            subt.task = task_id
            subt.completed = False
            subt.created_date = timezone.now()
            subt.save()
            return redirect('todo:detail', pk)
    else:
        form = SubTaskForm()

    return render(request, 'todo/subtask_edit.html', {'form':form, 'task':task_id, 'project':project})

@login_required
def edit_subtask(request, pk, sk):
    subtask = get_object_or_404(SubTask, pk=sk)
    task_id = subtask.task
    # task = Task.objects.get(pk=task_id)
    project = get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        form = SubTaskForm(request.POST, instance=subtask)
        if form.is_valid():
            subtask.save()
            return redirect('todo:detail', pk)
    else:
        form = SubTaskForm(instance=subtask)

    return render(request, 'todo/subtask_edit.html', {'form':form, 'task':task_id, 'project':project})

@login_required
def delete_subtask(request, pk, sk):
    subtask = get_object_or_404(SubTask, pk=sk)
    subtask.delete()
    return redirect('todo:detail', pk)

dissnitt/notes/templates/notes/by_tag_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load notes_app_filters %}
{% block head %}
    <title>Tags | Dissnitt</title>
    <link rel="stylesheet" href="{% static 'notes/css/notes.css' %}">
    <script type="text/javascript" src="{% static 'notes/javascript/notes.js' %}" ></script>
{% endblock %}
{% block page_header %}
    <h1>Tag: {{ tag.name }} </h1>
{% endblock %}
{% block sidepage %}
    <hr>
        <a href="{% url 'notes:new_note' %}">New Note</a>
    <hr>
    <h3 style="color: #304c89;" ><a href="{% url 'notes:tags' %}">Tags</a></h3>
    <div class="note_tags">
        {% for tag in tags %}
            <a href="{% url 'notes:by_tag' tag.id %}">{{tag.name}}</a>
        {% endfor %}
    </div>
{% endblock %}
{% block content %}
    <div class="note_index">
        {% for note in tag.note_set.all %}
         <p>
                <a class="note_title" href="{% url 'notes:detail' note.id %}">{{ note.title }}</a><br>
                    {{ note.created_date| date:"M d, Y" }}
                    | <a href="{% url 'notes:edit_note' note.id %}">Edit</a>
                    | <a href="{% url 'notes:delete_note' note.id %}">Delete</a>
                    |
                <a href="javascript:void(0)" onclick="toggleDetailsView('{{ note.id }}', 'link_{{ note.id }}')" id="link_{{note.id}}">
                    +Details
                </a>
            </p>
            <div class="note_details" id="{{note.id}}">
                <p class="note_body">
                    {{ note.body|truncatechars:100 }}
                </p>
                <div class="detail_tags">
                    {% for tag in note.tags.all|sort_by_name %}
                        <a href="{% url 'notes:by_tag' tag.id %}">{{ tag }}</a>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

dissnitt/notes/templates/notes/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load notes_app_filters %}
{% block head %}
    <title>Notes | Dissnitt</title>
    <link rel="stylesheet" href="{% static 'notes/css/notes.css' %}">
{% endblock %}
{% block page_header %}
    <h1>{{ note.title }}</h1>
{% endblock %}
{% block sidepage %}
     <hr>
        <a href="{% url 'notes:new_note' %}">New Note</a>
    <hr>
    <a href="{% url 'notes:edit_note' note.id %}">Edit</a><br>
    <a href="{% url 'notes:delete_note' note.id %}">Delete</a>
        <h3 style="color: #304c89;" ><a href="{% url 'notes:tags' %}">Tags</a></h3>
    <div class="note_tags">
        {% for tag in tags %}
            <a href="{% url 'notes:by_tag' tag.id %}">{{tag.name}}</a>
        {% endfor %}
    </div>
{% endblock %}
{% block content %}
    <p style="text-align: center;">Created: {{ note.created_date|date:"M d, Y" }}</p>
    <div class="dp_note_details">
        <p>
            {{ note.body| urlize | linebreaks }}
        </p>
        <div class="detail_tags">
            {% for tag in note.tags.all|sort_by_name %}
              <a href="{% url 'notes:by_tag' tag.id %}">{{ tag }}</a>
            {% endfor %}
        </div>
    </div>
    <div class="add_tags">
        <h3>Add Tag(s)</h3>
         <form method="POST">
             {% csrf_token %}
            <p>
                {{ form.non_field_errors }}
                {{ form.title.errors }}
            </p>
            <p>
                {{ form.name }}
            </p>
             <button class="nbutton" type="submit" >Add Tag</button>
         </form>
    </div>
{% endblock %}

dissnitt/notes/templates/notes/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load notes_app_filters %}
{% block head %}
    <title>Notes | Dissnitt</title>
    <link rel="stylesheet" href="{% static 'notes/css/notes.css' %}">
    <script type="text/javascript" src="{% static 'notes/javascript/notes.js' %}" ></script>
{% endblock %}
{% block page_header %}
    <h1>Notes</h1>
{% endblock %}
{% block sidepage %}
    <hr>
        <a href="{% url 'notes:new_note' %}">New Note</a>
    <hr>

    <h3 style="color: #304c89;" ><a href="{% url 'notes:tags' %}">Tags</a></h3>
    <div class="note_tags">
        {% for tag in tags %}
            <a href="{% url 'notes:by_tag' tag.id %}">{{tag.name}}</a>
        {% endfor %}
    </div>
{% endblock %}
{% block content %}
    <div class="note_index">
        {% for note in note_list %}
            <p>
                <a class="note_title" href="{% url 'notes:detail' note.id %}">{{ note.title }}</a><br>
                    {{ note.created_date| date:"M d, Y" }}
                    | <a href="{% url 'notes:edit_note' note.id %}">Edit</a>
                    | <a href="{% url 'notes:delete_note' note.id %}">Delete</a>
                    |
                <a href="javascript:void(0)" onclick="toggleDetailsView('{{ note.id }}', 'link_{{ note.id }}')" id="link_{{note.id}}">
                    +Details
                </a>
            </p>
            <div class="note_details" id="{{note.id}}">
                <p class="note_body">
                    {{ note.body|truncatechars:100 }}
                </p>
                <div class="detail_tags">
                    {% for tag in note.tags.all|sort_by_name %}
                        <a href="{% url 'notes:by_tag' tag.id %}">{{ tag }}</a>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

dissnitt/notes/templates/notes/note_new.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load notes_app_filters %}
{% block head %}
    <title>Notes | Dissnitt</title>
    <link rel="stylesheet" href="{% static 'notes/css/notes.css' %}">
{% endblock %}

{% block sidepage %}
    <hr>
    <h3 style="color: #304c89;" ><a href="{% url 'notes:tags' %}">Tags</a></h3>
    {% for note in notes %}
        <a href="{% url 'notes:detail' note.id %}">{{ note.title }}</a><br>
    {% endfor %}

{% endblock %}

{% block page_header %}
<h1>Create a New Note</h1>

{% endblock %}

{% block content %}

<div class="note_form">
    <form method="POST">
        {% csrf_token %}
        <p>
            {{ form.non_field_errors }}
            {{ form.title.errors }}
        </p>
        <p>
            {{ form.title }}
        </p>
        <p>
            {{ form.body.errors }}
        </p>
        <p>
            {{ form.body }}
        </p>
        <p>
            <button class="nbutton" type="submit" >Create New Note</button>
        </p>
    </form>

</div>
{% endblock %}

dissnitt/notes/templates/notes/tag_index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load notes_app_filters %}
{% block head %}
    <title>Tags | Dissnitt</title>
    <link rel="stylesheet" href="{% static 'notes/css/notes.css' %}">
    <script type="text/javascript" src="{% static 'notes/javascript/notes.js' %}" ></script>
{% endblock %}
{% block page_header %}
    <h1>All The Tags</h1>
{% endblock %}
{% block sidepage %}
    <hr>
        <a href="{% url 'notes:new_note' %}">New Note</a>
    <hr>

    <h3 style="color: #304c89;" ><a href="{% url 'notes:tags' %}">Tags</a></h3>
    <div class="note_tags">
        {% for tag in tag_list %}
            <a href="{% url 'notes:by_tag' tag.id %}">{{tag.name}}</a>
        {% endfor %}
    </div>
{% endblock %}
{% block content %}
 <div class="tag_index">
    {% for tag in tag_list|sort_tags_by_count_name %}
        <p>
            <a href="{% url 'notes:by_tag' tag.id %}">{{tag.name}}</a>
            ({{ tag.note_set.all|length }})
            <a href="javascript:void(0)" onclick="toggleDetailsView('tag_{{ tag.id }}', 'link_{{ tag.id }}')" id="link_{{tag.id}}">+Details</a>
            | <a href="{% url 'notes:delete_tag' tag.id %}">Delete</a><br>
            <div class="note_list" style="display: none;" id="tag_{{tag.id}}">
                <ul>
                    {% for note in tag.note_set.all %}
                        <li><a href="{% url 'notes:detail' note.id %}">{{ note.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </p>
     {% endfor %}
 </div>

{% endblock %}